export const products = [
	{
		id: 1,
		album: "Disintegration",
		band: "The Cure",
		year: 1989,
		category: "Vinilo",
		price: 30000,
		stock: 15,
		imageURL: "",
	},
	{
		id: 2,
		album: "Fin de Semana Salvaje",
		band: "Los Brujos",
		year: 1991,
		category: "Vinilo",
		price: 40000,
		stock: 5,
		imageURL: "",
	},
	{
		id: 3,
		album: "Tragic Kingdom",
		band: "No Doubt",
		year: 1995,
		category: "CD",
		price: 10000,
		stock: 10,
		imageURL: "",
	},
	{
		id: 4,
		album: "Dale Aborigen",
		band: "Todos Tus Muertos",
		year: 1994,
		category: "Cassette",
		price: 8000,
		stock: 12,
		imageURL: "",
	},
];
